version: '3.5'

networks:
  web:
  db:

services:
  doctrina:
    image: ${DOCKER_REGISTRY}doctrina
    container_name: doctrina-lrs
    build:
      context: ./Doctrina.WebUI
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - sql
    networks:
      - web
      - db

  sql:
    image: microsoft/mssql-server-linux
    container_name: doctrina-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pwd12345!
      - MSSQL_TCP_PORT=1433
    ports:
      - "1433:1433"
    volumes:
      - "c:/data/mssql/data:/var/opt/mssql/data"
    networks:
      db:
        aliases:
          - sql
