version: '3.5'

networks:
  web:
  db:

services:

  doctrina:
    image: doctrina:latest
    build:
      context: ./
      dockerfile: ./Doctrina.WebUI/Dockerfile
    depends_on:
      - data.sql
    volumes:
      - "c:/doctrina/app/logs:/app/logs"
    networks:
      - web
      - db

  data.sql:
    image: microsoft/mssql-server-linux
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pwd12345!
      - MSSQL_TCP_PORT=1433
    ports:
      - "5002:1433"
    volumes:
      - "c:/doctrina/mssql/data:/var/opt/mssql/data"
    networks:
      db:
        aliases:
          - sql
