version: '3.5'

services:
  doctrina:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DoctrinaDatabase=Server=sql;Database=DoctrinaDb;User Id=sa;Password='Pwd12345!'
    ports:
      - "8080:443"
      - "8081:80"